### ISSUE TITLE
Does not work when using arrow functions for describe

### ISSUE THREAD

**Issue by codeandcats** [pavel-purma/vscode-mocha-test-runner#1]
I'm using arrow functions for all my describe and it callbacks in my TypeScript project which this extension does not currently recognise.

Firstly let me say that I'm aware that Mocha recommends not using arrow functions for describes and its so that you get access to the this context it provides but I rarely (if ever) need to use it so I prefer to the terse, cleaner syntax that arrow functions provide, especially given one of the goals of mocha is to provide a minimal BDD syntax.

This is a very cool extension but we already have hundreds of tests that I don't want to switch to long-form function syntax.

If its not too much work to add support for arrow functions, I would dearly love this ability! ❤️

**Comment by CzBuCHi** [comment]
Added arrow function support in typescript - see [typescript project #2](https://github.com/pavel-purma/vscode-mocha-test-runner/tree/master/.vscode-test/tsa-project).  

If it still not working, please send me code example.

Cheers

**Comment by codeandcats** [comment]
Wow, thanks for the amazingly quick turnaround, I'll check it out shortly.
