### ISSUE TITLE
Javascript with react with .js extensions not supported

### ISSUE THREAD

**Issue by cgestes** [pavel-purma/vscode-mocha-test-runner#13]
Any idea about how to fix it?

Removing the language structure would work for me?

I can provide a patch if you guide me.

My configuration:

```javascript
  "mocha.options": {
    "compilers": "js:babel-core/register"
  },
  "mocha.glob": "**/*.test.js"
  "files.associations": {
    "*.js": "javascriptreact"
  },
```

**Comment by CzBuCHi** [comment]
i dont know anything about 'javascriptreact' but if it is sililar to typescript (has defined transform to ES5) then you must specify "mocha.sourceDir" where yours "javascriptreact" files are and "mocha.outputDir" where transpiled ES5 equivalents are (you may also specify "mocha.compilerScript" with is package.json script, that will transpile {mocha.sourceDir}/path/name.js to {mocha.outputDir}/path/name.js before running mocha ('path/name' is used to determine transpiled file from source) - manual run would be 'npm run name_of_script')

**Comment by cgestes** [comment]
Hi @CzBuCHi,

Let me explain my config:
The file associations line make vs code treats all js files as react files. (basically it is fine with jsx)

the mocha.options force the use of babel when running mocha.

The whole think is working, except that the language map expect my file to have a jsx extensions:
see here:
 https://github.com/pavel-purma/vscode-mocha-test-runner/blob/master/src/Utils.ts#L34

Why is this map useful? Can I just drop it, and accept all files that match the glob?

**Comment by cgestes** [comment]
BTW, it would make sense to add a config example for using babel with mocha, which is a very common setup.

**Comment by CzBuCHi** [comment]
@cgestes  https://github.com/pavel-purma/vscode-mocha-test-runner/tree/master/.vscode-test/es6-project is not babelish for you? :)

BTW: maybe documentation can be improved, but english is not my first language so i have no idea how :/

**Comment by CzBuCHi** [comment]
@cgestes to your first comment:
map is needed, because otherwise vscode will not show code lens.

**Comment by cgestes** [comment]
https://github.com/pavel-purma/vscode-mocha-test-runner/tree/master/.vscode-test/es6-project
This compiles the sources directly with babel, I much prefer using *babel-core/register* as commonly advertised everywhere. (sources are never out of sync).

https://github.com/pavel-purma/vscode-mocha-test-runner/blob/master/src/commands.ts#L88
This is my issue.

I dont think the extension should decide about the extensions of files. What do you think about making it rely only on the language as vs code knows it?

Otherwise we force the user to have .jsx for react code, which is so 2016.

:D

**Comment by CzBuCHi** [comment]
- i would need to do some research about babel-core/register - making test file auto-compile was planed from start, but i never get to it...

- im not sure why i put #L88 check there ... i think it was to filter out non-test file early (aka: premature optimalization) and can be ommited...

**Comment by cgestes** [comment]
Ok, I start to understand what language is used for and why you strip the extension..
No easy way to map between the compiled folder and source folder.

I guess I have a patch that addresses this part: https://github.com/pavel-purma/vscode-mocha-test-runner/pull/14

**Comment by cgestes** [comment]
fixed with https://github.com/pavel-purma/vscode-mocha-test-runner/pull/14
