### ISSUE TITLE
[feature] display logs and failure informations

### ISSUE THREAD

**Issue by cgestes** [pavel-purma/vscode-mocha-test-runner#15]
Would it be possible to display the output of mocha and also why the failing tests failed?

Feel free to close, if this is already provided and I just wasn't able to run it properly. (I am thinking about the other issues we are currently fixing)

**Comment by CzBuCHi** [comment]
i think thats already there: (used es5-project\src\test\utility.test.js)
when i run first two test (by commenting out rest) log looks like this:
```
Grep pattern:
  ^Utility

Test file(s):
c:\projects\github\vscode-mocha-test-runner\.vscode-test\es5-project\src\test\utility.test.js

Starting mocha ...

  Utility
    √ Success (1005ms)
    1) Fail

  1 passing (1s)
  1 failing

  1) Utility
       Fail:

      AssertionError: expected 3 to equal 0
      + expected - actual

      -3
      +0
      
      at Context.<anonymous> (src\test\utility.test.js:15:36)
```
with tells u that first test succed and second fails because 3 != 0 ...

**Comment by cgestes** [comment]
Ok, I dont have log at all. I guess that's my main issue.
