### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by ktmn** [pavel-purma/vscode-mocha-test-runner#2]
Here are my imports

```
import 'babel-polyfill'
import Nightmare from 'nightmare'
import { expect } from 'chai'
import config from '../config'
var should = require('chai').should()
require('mocha-generators').install()
```

I can run the tests with 

`cd test && mocha --compilers js:babel-core/register`

(All node modules for tests are installed in the test directory.)

So I set the workspace config to

```
"mocha.sourceDir": "test",
"mocha.outputDir": "test", // not sure what that does
"mocha.options": {
  "compilers": "js:babel-core/register"
}
```
But when I do "Run all tests in current file" I get:

```
Applying Mocha options:
  --compilers: js:babel-core/register

Test file(s):
/project/test/foo/bar.test.js

Starting mocha ...

Unexpected token import

```

If I do 

`cd test && mocha --compilers js:babel-core/register ./foo/bar.test.js`

it works, so why doesn't it work with the plugin even though it says it's applying the compilers argument?

Could be useful if it output the command it's using.

**Comment by ktmn** [comment]
I also tried compiling the file manually with babel.

Running the compiled file with mocha works, running it through the plugin outputs

```
Starting mocha ...


  Describe1
    Describe2

undefined
```

**Comment by CzBuCHi** [comment]
is do not fully understand how  **`--compilers: js:babel-core/register`** works so i usually have console window open in background with **`npm run test:watch`** in it (with calls to **`babel --out-dir .output --ignore=node_modules,dist --watch src`** or something simillar) and this configuration:
```js
"mocha.sourceDir": "src",
"mocha.outputDir": ".output"
```
this way my plugin dont need to transpile sources internally ... look at [es6-project](https://github.com/pavel-purma/vscode-mocha-test-runner/tree/master/.vscode-test/es6-project) 
for working sample

"mocha.sourceDir" is directory, where sources are - anything, that can be transpiled to es5
"mocha.outputDir" is directory with transpiled es5 sources

im using these two to show correct codelens (im planing to use sourcemaps to find original source, but that occured to me during writing this coment ... :)

edit: to second comment: undefined is probably forgoten debug console.log ...

**Comment by ktmn** [comment]
Basically it seems this plugin doesn't work with [nightmare](https://github.com/segmentio/nightmare), but I wonder why.

Here's the test I tried:

```
var Nightmare = require('nightmare');
var expect = require('chai').expect; // jshint ignore:line

describe('test duckduckgo search results', function() {
  this.timeout('30s')
  it('should find the nightmare github link first', function(done) {
    var nightmare = Nightmare({show: true})
    nightmare
      .goto('https://duckduckgo.com')
      .type('#search_form_input_homepage', 'github nightmare')
      .click('#search_button_homepage')
      .wait('#zero_click_wrapper .c-info__title a')
      .evaluate(function () {
        return document.querySelector('#zero_click_wrapper .c-info__title a').href
      })
      .end()
      .then(function(link) {
        expect(link).to.equal('https://github.com/segmentio/nightmare');
        done();
      })
  });
});
```

Here's the output.

```
No Mocha options are configured. (I have options and it seems to be using them...)
  You can set it under File > Preferences > Workspace Settings.

Grep pattern:
  ^(test duckduckgo search results should find the nightmare github link first)$

Test file(s):
/project/test/.output/duckduckgo.test.js

Starting mocha ...


  test duckduckgo search results

undefined
```

Any ideas?

---

> is do not fully understand how --compilers: js:babel-core/register works 

I don't know the specifics either but it allows to run code without having to compile it first, which is rather convenient.

**Comment by CzBuCHi** [comment]
tried your code and got same error ...
after debugging tru plugin sources i found a bug - error message is not printed to output (that undefined message)...

real problem is this:

"Nightmare runner error:

	TypeError: Cannot read property 'dock' of undefined
	    at Object.<anonymous> (c:\projects\vscode\vscode-mocha-test-runner\.vscode-test\es6-project\node_modules\nightmare\lib\runner.js:58:29)
	    at Object.<anonymous> (c:\projects\vscode\vscode-mocha-test-runner\.vscode-test\es6-project\node_modules\nightmare\lib\runner.js:652:3)
	    at Module._compile (module.js:571:32)
	    at Object.Module._extensions..js (module.js:580:10)
	    at Module.load (module.js:488:32)
	    at tryModuleLoad (module.js:447:12)
	    at Function.Module._load (module.js:439:3)
	    at Module.runMain (module.js:605:10)
	    at run (bootstrap_node.js:424:7)
	    at startup (bootstrap_node.js:147:9)
"

Edit: looks like plugin dont like electron ... i will try to create working electron sample project later..

**Comment by ktmn** [comment]
Awesome, thanks! I can't wait

**Comment by ktmn** [comment]
@CzBuCHi If you're unable to get this to work with the current system, what if there was a way to just run a command in the VS Code integrated terminal by clicking on the lens? 

In some configuration I could specify the command `"yarn test $lens"` and the plugin would replace `$lens` with the grep pattern and current file name and then run the command in the terminal, which would display the output for me, but wouldn't have to send any data back to the lens. It would just be a convenient way to run specific tests by clicking on the lens and would work with any setup.

**Comment by CzBuCHi** [comment]
i created test project at https://github.com/pavel-purma/vscode-mocha-test-runner/tree/master/.vscode-test/nightmare-project for this and now trying to reproduce error by calling test outside vscode with no success:
- by calling `node run.js` in testing directory  test will succeed
- by calling exactly same test file from plugin i get `Cannot read property 'dock' of undefined`

@ktmn external command should work ...
- technically i would fork your code instead of internal TestProcess.js and you would call to yarn ...
- your script would need to implement some sort of  request-response interfaces... (probably same as  TestProcess.js, but need to make it public)
- not sure what vscode debugger (node debugger) would do with yarn ...

i will continue with my investigation ...
