### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by oliversalzburg** [pavel-purma/vscode-mocha-test-runner#21]
This extension doesn't seem to do anything in 1.19.2. I installed it, set the `nodeExec` path and started my Mocha test suite. There is no noticeable difference to how everything behaved before installing the extension.

**Comment by CzBuCHi** [comment]
Sorry of hearing about that ... sadly i dont have any time right now to investigate :(

anyway main reason for this extension was to be able debug mocha tests from vscode - which can be now done easyier: [see this](https://gist.github.com/paambaati/54d33e409b4f7cf059cc) ...

**Comment by oliversalzburg** [comment]
Oh. That's what I have been using and was looking for something that might let me re-run individual tests. I ended up using https://wallabyjs.com

Thanks for the reply :)
