### ISSUE TITLE
mocha.glob postfix is not respected

### ISSUE THREAD

**Issue by balazser** [pavel-purma/vscode-mocha-test-runner#3]
My tests are named as "name.spec.js". These are not respected even if I modify the   "mocha.glob": to "**/*.spec.js" in the settings.
Am I doing anything wrong?
I cloned the source to test it, and I experienced same. After the glob is modified the test.js postfix is still respected.

**Comment by CzBuCHi** [comment]
it was a bug in codelens provider - hardcoded glob pattern ... fixed in 0.1.4

**Comment by balazser** [comment]
thank you 🥇
