### ISSUE TITLE
Always Failed

### ISSUE THREAD

**Issue by CallMeLaNN** [pavel-purma/vscode-mocha-test-runner#5]
I got a simple mocha setup but clicking `Inconclusive` or `Fail` will always turn to `Fail` even for always success `assert.ok(true)`.

There is no nothing in the OUTPUT except this:

```
No Mocha options are configured.
  You can set it under File > Preferences > Workspace Settings.

Test file(s):
c:\...\test\services\try.test.js

Starting mocha ...
```

I expect there is an error stack trace etc in the OUTPUT.

**Comment by CzBuCHi** [comment]
just tried reproduce your fail with this (es5) code:
```js
const assert = require('chai').assert;
describe('Test', function() {
    it('test', function() {
        assert.ok(true);
    });
});
```
and it will succeed ... so i need more info.

btw: these test both fails: (both have same full name 'Test test') and plugin cant differentiate them, so it runs all of them and if one fails all fails - maybe this is your case?
```js
const assert = require('chai').assert;
describe('Test', function() {
    it('test', function() {
        assert.ok(true);
    });
    it('test', function() {
        assert.ok(false);
    });
});
```

**Comment by CallMeLaNN** [comment]
Actually, my concern was I am expecting there is an error msg and stack trace etc in the OUTPUT when the test failed. I saw the output logged until `Starting mocha ...` only. However it just failed without any clue.

Today, I retry again all cases from empty project up to my `feathers` app but turns out that everything works perfect including expecting the error message and stack trace if the test failed.

Maybe there was something wrong in my VSCode or my machine state during that time. Most probably this extension have problem on running `mocha` for the first time after install and reload this extension because it stuck at `Starting mocha ...` and it shows `Fail`.
