### ISSUE TITLE
doesn't work in vscode 1.13.1?

### ISSUE THREAD

**Issue by ceres629** [pavel-purma/vscode-mocha-test-runner#6]
Is there something that needs to be done to get this working?
I installed the addon, cloned the ES6 test project did a yarn install, opened Foo.test.js and nothing happened.

In vscode 1.13.1 on osx.

**Comment by CzBuCHi** [comment]
hello, i forget to add `"mocha.enabled": true` to settings.json file in example projects when config was changed ... that should fix your issue ...

**Comment by ceres629** [comment]
Thanks that did the trick!
