### ISSUE TITLE
Setting "mocha.enabled" requires a reload.

### ISSUE THREAD

**Issue by literalsands** [pavel-purma/vscode-mocha-test-runner#7]
Adding the setting { "mocha.enabled": true } before without reloading results in cryptic (Command not found "vscode-mocha-test-runner.run-file-tests") error message.

**Comment by CzBuCHi** [comment]
thats vscode behavior - settings is loaded in start and then not reloaded on change ... (at least that i understand it ..)

**Comment by literalsands** [comment]
Most settings made in settings.json are reflected immediately and do not require a reload. But, this error could at least be changed to suggest the user to reloads, rather than the uninformative "not found" message given.

**Comment by CzBuCHi** [comment]
after reviewing hot i read config i think i found why settings where not changing without restart - published fix v0.2.1 for it
and as secondthing i changed how extension react if not enabled - shows notification message instead of some log in console ...

**Comment by literalsands** [comment]
Nice! That fixes the hiccup I had during my initial setup process.
