### ISSUE TITLE
mocha.env not working

### ISSUE THREAD

**Issue by dj90sz** [pavel-purma/vscode-mocha-test-runner#9]
I'm trying to utilise **mocha.env** config to set _NODE_ENV=test_, however I'm unable to do so. 
Here's my settings.json:
```
{
  "mocha.env": {
    "NODE_ENV": "test"
  }
}
```

I tried looking into the source code but can't find anywhere that the variable is being used. Can someone please enlighten me? Thanks

**Comment by CzBuCHi** [comment]
im statring mocha programically and i dont know how to set env in there .... see [set-options](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically#set-options) from mocha doc.
env variable in config is not used (frankly, i forget to remove it when i didnt found method to use it..)

not sure if it would work if i set env during forking node with runs mocha ... (TestSunner.ts; line 40)

**Comment by dj90sz** [comment]
I was looking into your idea of setting the env during the forking and I found [this](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options). Looks like you can add `env: config.env` to the options object!

**Comment by CzBuCHi** [comment]
added env param to fork options, please tell me if itis working, because i have no idea how env works in mocha ... :/

**Comment by dj90sz** [comment]
@CzBuCHi it works!

You just need to set env like this in your vscode settings
```
{
  "mocha.env": {
    "NODE_ENV": "test"
  }
}
```

Thanks for the quick fix! 👍
